# Generated by Django 4.2.30 on 2026-05-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sync_state', serialize=False, to='learning.learner')),
                ('last_content_sync', models.DateTimeField(blank=True, null=True)),
                ('last_progress_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
