# Generated by Django 4.2.30 on 2026-05-06 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect'), ('PARTIAL', 'Partial')], max_length=16)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.item')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.learner')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_due', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_states', to='content.item')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_states', to='learning.learner')),
            ],
            options={
                'indexes': [models.Index(fields=['learner', 'next_due'], name='learning_it_learner_ba09da_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='itemstate',
            constraint=models.UniqueConstraint(fields=('learner', 'item'), name='unique_learner_item_state'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['learner', 'timestamp'], name='learning_at_learner_77518a_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['item', 'timestamp'], name='learning_at_item_id_e73229_idx'),
        ),
    ]
