# Generated by Django 4.2.30 on 2026-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='is_teacher_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learner',
            name='teacher_proposal_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
    ]
