# Generated by Django 4.2.30 on 2026-05-06 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(db_index=True, max_length=128)),
                ('level', models.CharField(db_index=True, max_length=64)),
                ('license_type', models.CharField(choices=[('CC-BY', 'CC BY'), ('CC-BY-SA', 'CC BY-SA'), ('CC-BY-NC', 'CC BY-NC'), ('CC-BY-NC-SA', 'CC BY-NC-SA'), ('CC-BY-ND', 'CC BY-ND'), ('CC-BY-NC-ND', 'CC BY-NC-ND'), ('CC0', 'CC0 (Public Domain)'), ('PD', 'Public Domain'), ('ALL_RIGHTS', 'All Rights Reserved')], max_length=32)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('OTHER', 'Other')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('url', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('content_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.contentunit')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CLOZE', 'Cloze / Fill-in-the-blank'), ('TRUE_FALSE', 'True / False'), ('LISTEN_ANSWER', 'Listen and Answer'), ('SPEAK_REPEAT', 'Speak and Repeat')], max_length=24)),
                ('prompt', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('difficulty_initial', models.FloatField(blank=True, null=True)),
                ('content_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.contentunit')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='content.tag')),
            ],
            options={
                'ordering': ['item_type'],
            },
        ),
        migrations.CreateModel(
            name='ContentVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=12)),
                ('script', models.CharField(default='Latin', max_length=32)),
                ('body', models.TextField()),
                ('is_official_translation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='content.contentunit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contentvariant',
            constraint=models.UniqueConstraint(fields=('content_unit', 'language_code'), name='unique_content_language'),
        ),
    ]
