# Generated by Django 4.2.30 on 2026-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sort_order', 'item_type']},
        ),
        migrations.AddField(
            model_name='item',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='item',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CLOZE', 'Cloze / Fill-in-the-blank'), ('TRUE_FALSE', 'True / False'), ('LISTEN_ANSWER', 'Listen and Answer'), ('SPEAK_REPEAT', 'Speak and Repeat'), ('PRONUNCIATION', 'Pronunciation Practice'), ('MATH_INPUT', 'Math Input'), ('MATCHING', 'Matching Pairs'), ('SORTING', 'Sorting / Ordering'), ('DIAGRAM_LABEL', 'Diagram Label'), ('WRITING', 'Writing / Open Response')], max_length=24),
        ),
    ]
