# Generated by Django 4.2.30 on 2026-05-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_item_options_item_hint_item_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_target_audio',
            field=models.FileField(blank=True, null=True, upload_to='ai_pronunciation/'),
        ),
        migrations.AddField(
            model_name='item',
            name='ai_target_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='media_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_items', to='content.mediaresource'),
        ),
    ]
