# Generated by Django 4.2.30 on 2026-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_item_ai_target_audio_item_ai_target_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CLOZE', 'Cloze / Fill-in-the-blank'), ('TRUE_FALSE', 'True / False'), ('LISTEN_ANSWER', 'Listen and Answer'), ('SPEAK_REPEAT', 'Speak and Repeat'), ('PRONUNCIATION', 'Pronunciation Practice'), ('MATH_INPUT', 'Math Input'), ('MATCHING', 'Matching Pairs'), ('SORTING', 'Sorting / Ordering'), ('DIAGRAM_LABEL', 'Diagram Label'), ('WRITING', 'Writing / Open Response'), ('ADVANCED_CANVAS_GAME', 'Advanced Canvas Game')], max_length=24),
        ),
    ]
