# Generated by Django 4.2.30 on 2026-05-06 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='⭐', max_length=32)),
                ('category', models.CharField(db_index=True, default='general', max_length=64)),
                ('required_xp', models.PositiveIntegerField(default=0)),
                ('required_streak', models.PositiveIntegerField(default=0)),
                ('required_correct_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'required_xp'],
            },
        ),
        migrations.CreateModel(
            name='LearnerStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_incorrect', models.PositiveIntegerField(default=0)),
                ('total_partial', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('daily_xp_goal', models.PositiveIntegerField(default=50)),
                ('daily_xp_earned', models.PositiveIntegerField(default=0)),
                ('daily_xp_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='learning.learner')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded', to='gamification.badge')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='learning.learner')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('items_completed', models.PositiveIntegerField(default=0)),
                ('seconds_practiced', models.PositiveIntegerField(default=0)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='learning.learner')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='learnerbadge',
            constraint=models.UniqueConstraint(fields=('learner', 'badge'), name='unique_learner_badge'),
        ),
        migrations.AddConstraint(
            model_name='dailyactivity',
            constraint=models.UniqueConstraint(fields=('learner', 'date'), name='unique_learner_date'),
        ),
    ]
