# Generated by Django 4.2.30 on 2026-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_canvasgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasgame',
            name='game_code',
            field=models.TextField(blank=True, help_text='JavaScript/TypeScript code for the game logic', null=True),
        ),
        migrations.AddConstraint(
            model_name='canvasgame',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_teacher_game_name', violation_error_message='A game with this name already exists for this teacher.'),
        ),
    ]
